### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [losaki/PrefectureQuiz#1]
遅くなってしまい申し訳ございません。。
※ 確認後closeしていただけたらと思います。

## サービスレビュー

* 写真投稿 x クイズの組み合わせのアイデア、大変おもしろいです！
* 写真をもっと投稿しやすくする為に「◯◯な風景」や「◯◯な場所」みたいにテーマを絞って募集をかけたりするとユーザ側も大喜利的に投稿してくれるかなと思います。
* あとはその写真とクイズの画像を合成してOGPに設定するとソーシャルでも拡散しやすくなりそうだなと。
* アイデア自体はすごく面白いので、次の機能拡張はマーケティングを意識してみてください。

## コードレビュー

https://github.com/losaki/PrefectureQuiz/blob/1e87f04924c56ba57cb08185058ec4ce37ab4138/app/controllers/quizzes_controller.rb#L5-L6

ソートが固定であれば、無理にransackのソート使わずにActiveRecordのorderを使ったほうがいいかなと思います。

https://github.com/losaki/PrefectureQuiz/blob/1e87f04924c56ba57cb08185058ec4ce37ab4138/app/controllers/quizzes_controller.rb#L24-L27

今の形でも全然悪くはないのですが、1..47を配列変換して予め対象のprefecture_idを削除しておけばredo処理をなくせるので処理回数を減らせるかなと思いました。

```
prefecture_ids = (1..47).to_a
prefecture_ids.delete(@quiz.prefecture_id)
choice. prefecture_id = prefecture_ids.sample
```

* 重箱の隅をつつくような形になっちゃいましたが、概ねきれいに書けているので、特に大きな指摘はないかなと思いました。
* コードの厚みを持たせる為にもう少し複雑なロジックを書けると就活向けとしてはいいかなと思うので、ロジック少し複雑化するような機能も考えてみてください
* ある程度機能が出来たところでsystem specを中心にテストを埋めていってください。その後UI調整とREADMEにスクショを貼るなどきれいに整えていただけたら就活準備完了となります。

**Comment by losaki** [comment]
ありがとうございます！！
